name: muz_hesap_defteri
description: Muz Hesap Defteri uygulamasi.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.0
  intl: ^0.20.2
  uuid: ^4.0.0
  path_provider: ^2.0.15
  pdf: ^3.10.0
  printing: ^5.10.0
  excel: ^2.0.1
  share_plus: ^7.1.0
  google_fonts: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
